(add-to-list 'load-path (concat user-emacs-directory "lisp/"))


(require 'mat-bootstrap)
(require 'mat-ui)
;(require 'mat-perf)
(require 'mat-env)
(require 'mat-bindings)
(require 'mat-session)
(require 'mat-git)
(require 'mat-qol)
(require 'mat-backup)
(require 'mat-dired)
(require 'mat-minibuffer)
(require 'mat-completion)
(require 'mat-workspace)
(require 'mat-search)
(require 'mat-js)
(require 'mat-ts)
(require 'mat-project)
(require 'mat-md)
(require 'mat-prog)
(require 'mat-profiling)
(require 'mat-diff)
;(require 'mat-lsp)
(require 'mat-clojure-lsp)
(require 'mat-service)
(require 'mat-command)
;(require 'mat-org)
(require 'mat-info)
(require 'mat-snippet)
;(require 'mat-modeline)
(require 'mat-evil)
(require 'mat-term)
(require 'mat-pass)
(require 'mat-http)
(require 'mat-centered)
