(add-to-list 'load-path (concat user-emacs-directory "lisp/"))

(require 'mat-bootstrap)
(require 'mat-ui)
(require 'mat-ivy)
(require 'mat-modeline)
(require 'mat-rainbow)
(require 'mat-evil)
(require 'mat-bindings)
(require 'mat-project)
(require 'mat-git)
(require 'mat-org)
(require 'mat-lsp)
(require 'mat-company)
(require 'mat-eshell)
(require 'mat-dired)
;(require 'mat-clojure-lsp)
